import 'package:get/get.dart';

class Internationalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "token_number": "Token Number",
          "created_user": "Created User",
          "cancelled_user": "Cancelled User",
          "cancelled_time": "Cancelled Time",
          "tax_scheme": "Tax Scheme",
          "created_date": "Created Date",
          "tax_type": "Tax Type",
          "product_image": "product Image",
          "sales_return_product_details": "Sales Return ProductDetails",
          "created_username": "Created Username",
          "reward_amount": "Reward Amount",
          "reward_point": "Reward Point",
          "round_off": "Round Off",
          "department": "Department",
          "Serial_no": "Serial No",
          'hellow': 'write',
          'credit': "Credit",
          'unit_rate': 'Unit rate',
          'unit_discount': 'Unit discount',
          'total_tax': 'Total tax',
          'offers': 'Offers',
          "bill_count": 'Bill Count',
          'purchase': 'Purchase',
          'stock': 'Stock',
          'not_free': 'Not free',
          'non_stock': "Non Stock",
          'sales_return_restaurant': 'Sales Return Restaurant',
          'customer_mobile': 'Customer Mobile',
          'customer_address': 'Customer Address',
          'stock_date': 'Stock Date',
          'stock_opening': 'Stock Opening',
          'stock_adjustment': 'Stock Adjustment',
          'stock_transfer': 'Stock Transfer',
          'stock_summary_details': 'Stock Summary Details',
          'stock_details': 'Stock Details',
          'remove': 'Remove',
          'return': 'Return',
          'loyalty': 'Loyalty',
          'receipt_allocation': 'Receipt Allocation',
          'customer_bill': 'Customer Bill',
          'invoice': 'Invoice',
          "voucher": "Voucher",
          "voucher_type": "Voucher Type",
          'inventory': 'Inventory',
          'restaurant': 'Restaurant',
          '10 coins:1 AED': '10 coins:1 AED',
          'purchase_return': 'Purchase Return',
          'purchase_amount': 'Purchase Amount',
          'purchase_amount_with_tax': 'PurchaseAmountWithTax',
          'inc': 'INC',
          'map_the_titles_accordingly': "Map the titles Accordingly",
          'subtotal': 'SubTotal',
          'sales_return': 'Sales Return',
          'sales_amount': 'Sales Amount',
          'sales_amount_with_tax': 'SalesAmountWithTax',
          'add_stock': 'Add Stock',
          "cancel_sales_report": "Canceled Sales Report",
          'exc': 'EXC',
          'offer_id': 'Offer Id',
          'offer_name': 'Offer Name',
          'time_from': 'Time From',
          'start_date': 'Start Date',
          "payment_allocation": "Payment Allocation",
          'expense_details': 'Expense Details',
          'id': 'ID',
          'from': 'From',
          'purchase_date': 'Purchase Date',
          'invoice_no': 'Invoice No',
          'no_tax': 'No tax',
          'is_free': 'Is Free',
          'add_product': 'Add Product',
          'to': 'To',
          'gross_total': 'Gross Total',
          'tax_amnt': 'Tax Amount',
          'net_total': 'Net Total',
          'add_loyalty': 'Add Loyalty',
          'supplier': 'Supplier',
          'code': 'Code',
          'outstanding': 'Outstanding',
          'delivery_provider': 'Delivery Provider',
          'date': 'Date',
          'type_id': 'Type Id',
          'sales_type': 'Sales Type',
          'type': 'Type',
          "end_date": 'End Date',
          'transaction_type': 'Transaction type',
          'time_to': 'Time to',
          'amount': 'Amount',
          'receipt': 'Receipt',
          'please_enter_supplier': 'Please enter supplier',
          'please_enter_product': 'Please enter product',
          'please_enter_sales_no': 'Please enter sales no',
          'select_relevant_product_id': 'Select relevant product id',
          'payment': 'Payment',
          'from_account': 'From Account',
          'to_account': 'To Account',
          'expense': 'Expense',
          'date_from': 'date_to',
          'offer_days': 'Offer days',
          'offer_rate_is_empty': 'Offer rate is empty',
          'offer_rate': 'Offer rate',
          'offer_type': 'Offer type',
          'rate_type': 'Rate type',
          "no_supplier_details_stored": "No supplier details stored",
          'product_based_offer': 'Product based offer',
          'bill_wise_offer': 'Bill wise offer',
          'offer': 'Offer',
          'monday': 'Monday',
          'tuesday': 'Tuesday',
          'wednesday': 'Wednesday',
          'thursday': 'Thursday',
          'friday': 'Friday',
          'saturday': 'Saturday',
          'sunday': 'Sunday',
          'address_3': "Address 3",
          "commission": "Commission",
          'please_enter_a_valid_number': 'Please enter a valid number',
          "commission_type": "Commission Type",
          "fill_in_commission": "Fill in Commission",
          "flat": "Flat",
          'accounts': 'Accounts',
          'payment_type_list': 'Payment Type List',
          'details': 'Details',
          'account_name': 'Account Name',
          "percentage": "Percentage",
          'debit': "Debit",
          'select_account': 'Select Account',
          'login': "LOGIN",
          'payment_type': 'Payment Type',
          'please_fill_in': 'Please fill in',
          'upiId': 'UPI ID',
          'remarks': 'Remarks',
          'enter_username': "Enter Username",
          'enter_password': "Enter Password",
          'work_in_progress': "Work in progress",
          "print_bills": "Print Bills",
          "pay": "Pay",
          "payment_method": "Payment Method",
          "payment_details": 'Payment Details',
          "category": "Category",
          "create": "Create",
          "edit": "Edit",
          "settings": "Settings",
          "list": "List",
          "dashboard": "Dashboard",
          "try_again": "TRY AGAIN",
          "name_is_empty": "Name is empty",
          "name": "Name",
          "success": "Success",
          "categories": "Categories",
          "search_here": "Search here",
          "image": "Image",
          "status": "Status",
          "empty_list": "Empty List",
          "full_documents_loaded": "Full documents loaded",
          "no_internet_connection_found": "No interner connection found",
          "user": "User",
          "email": "Email",
          "email_is_empty": "Email is empty",
          "password_is_empty": "Password is empty",
          "password": "Password",
          "users": "Users",
          "table": "Table",
          "tables": "Tables",
          "chairs": "Chairs",
          "add_chair": "Add Chair",
          "chair_name_is_empty": "Chair name is empty",
          "chair_name": "Chair name",
          "id_not_found": "ID Not found",
          "view": "View",
          "₹": "₹",
          'please_enter_a_number': 'Please enter a number',
          "kitchan_analysis_report": "Kitchen Analysis Report",
          "kitchen": "Kitchen",
          "counter": "Counter",
          "counters": "Counters",
          "kitchens": "Kitchens",
          "select_variant": "Select variant",
          "delivery_scope": "Delivery Scope",
          "credit_days_is_empty": "Credit Days is empty",
          "please_fill_in_correctly": "Please fill in correctly",
          "mobile_is_empty": "Mobile is empty ",
          "city_is_empty": "City is Empty",
          "address_1": "Address 1",
          "address_2": "Address 2",
          "address_is_empty": "Address is Empty",
          "property": "Property",
          "properties": "Properties",
          "items": "Items",
          "item_name_is_empty": "Item name is empty",
          "item_name": "Item name",
          "add_item": "Add item ",
          "change_colour": "Change colour ",
          "colour": "Colour ",
          "tax": "Tax ",
          "taxes": "Taxes ",
          "taxe_rate": "Taxe Rate ",
          "taxe_rate_is_empty": "Taxe rate is Empty ",
          "variant": "Variant",
          "variants": "Variants",
          "product": "Product",
          "products": "Products",
          "address1": "Address 1",
          "address2": "Address 2",
          "city": "City",
          "credit_limit": "Credit Limit",
          "credit_days": "Credit Days",
          "code_is_empty": "Code is empty",
          "name_in_local_optional": "Name in local*",
          "hsn_optional": "HSN*",
          "add_tax": "Add Tax",
          "add_rate": "Add Rate",
          "tax_name_is_empty": "Tax name is empty",
          "tax_name": "Tax name",
          "add_property": "Add Property",
          "rates": "Rates",
          "unit": "Unit",
          "quantity": "Quantity",
          "quantity_is_empty": "Quantity is empty",
          "barcode": "Barcode",
          "barcode_is_empty": "Barcode is empty",
          "rate": "Rate",
          "rate_is_empty": "Rate is empty",
          "description": "Description",
          "description_is_empty": "Description is empty",
          "waiter": "Waiter",
          "casher": "Casher",
          "unknown_status_code": "Unknown status code",
          "unknown": "Unknown",
          "delivery_counter": "Delivery Counter",
          "driver": "Driver",
          "add_payment": "Add Payment",
          "create_order": "Create Order",
          "edit_order": "Edit Order",
          "customer": "Customer",
          "cash": "Cash",
          "net_amount": "Net Amount",
          "dine": "Dine",
          "dine_in": "Dine in",
          "take_away": "Take Away",
          "delivery": "Delivery",
          "online": "Online",
          "online_payment": "Online Payment",
          "balance": 'Balance',
          "balance_is_empty": "Balance is Empty",
          "opening_balance": "Opening Balance",
          "opening_cash": "Opening cash",
          "closing_cash": "Closing cash",
          "cash_sales": "Cash sales",
          "total_expense": "Total expense",
          "opening_balance_sign": "Opening Balance Sign",
          "item": "Item",
          "qty": "Qty",
          "holding": "Holding",
          "placed": "Placed",
          "completed": "Completed",
          "cancelled": "Cancelled",
          "rejected": "Rejected",
          "kitchen_status": "Kitchen status",
          "update": "Update",
          "deliveryBoyAssigned": "Delivery Boy Assigned",
          "deliveryBoyPicked": "Delivery Boy Picked",
          "delivered": "Delivered",
          "customerRejected": "Customer Rejected",
          "customerCancelled": "Customer Cancelled",
          "thirdPartyPickupCompleted": "Third Party Pickup Completed",
          "customerPickupCompleted": "Customer Pickup Completed",
          "kitchenPreparing": "Kitchen Preparing",
          "kitchenCompleted": "Kitchen Completed",
          "kitchenPacked": "Kitchen Packed",
          "kitchenServed": "Kitchen Served",
          "codeNotMatch": "Code not match",
          "qrBarcodeReaderWorkWithAndroidOrIos":
              "Qr / Barcode reader work with Android and IOS",
          "paymentStatus": "Payment Status",
          "cart_is_empty": "Cart is empty",
          "select_table": "Select table",
          "customer_name": "Customer name",
          "phone": "Phone",
          "address": "Address",
          "select_provider": "Select provider",
          "ref_no": "Ref NO",
          "return_date": "Return date",
          "sales_return_list": "Sales Return List",
          "select_driver": "Select driver",
          "table_not_selected": "Table Not selected",
          "customer_name_is_empty": "Customer name is empty",
          "customer_phone_is_empty": "Customer phone is empty",
          "customer_address_is_empty": "Customer address is empty",
          "delivery_provider_not_selected": "Delivery provider not selected",
          "delivery_staff_not_selected": "Delivery staff not selected",
          "passcode_is_empty": "Passcode is empty",
          "passcode": "Passcode",
          "texts_are_empty": "Texts are empty",
          "admin": "Admin",
          "cashier": "Cashier",
          "bill_status": "Bill Status",
          "order": "Order",
          "token": "Token",
          "prefix": "Prefix",
          "no": "No",
          "new": "New",
          'mobile_2': 'Mobile 2',
          "orders": "Orders",
          "delete": "Delete",
          "error": "Error",
          "select_user_role": "Select user role",
          "all": "All",
          "local": "Local",
          "hsn": "HSN",
          "name_in_english": "Name In English",
          "name_in_english_is_empty": "Name in english is empty",
          "mobile": "Mobile",
          "work_time": "Work time",
          "search": "Search",
          "total": "Total",
          "remining": "Remining",
          "tender_cash": "Tender Cash",
          "rem": "Rem",
          "denomination": "Denomination",
          "add_denomination": "Add Denomination",
          "text": "Text",
          "multiplier": "Multiplier",
          "bulk_import": "Bulk Import",
          "CASH": 'CASH',
          'CREDIT': 'CREDIT',
          'c': "C",
          "custom": "Custom",
          "single_seat_table_count": "Single seat table count",
          "double_seat_table_count": "Double seat table count",
          "six_seat_table_count": "Six seat table count",
          "four_seat_table_count": "Four seat table count",
          "tables_are_ampty": "Tables are empty",
          "chair_count": "Chairs count",
          "arrangements": "Arrangements",
          "order_view_sort": "Order View Sort",
          "table_count": "Tables count",
          "submit": "Submit",
          "global_settings": "Global Settings",
          "local_settings": "Local Settings",
          "empty": "empty",
          "ask_passcode_while_order_taking": "Ask passcode while order taking",
          "show_on_screen_keyboard": "Show on screen keyboard",
          "is_show_to_customer": "Is show to customer",
          "effective_time_optional": "Effective time (optional)",
          "start_time": "Start time",
          "end_time": "End time",
          "printer_ip": "Printer ip",
          "reorder_level": "Reorder Level",
          "no_stock_item": "No stock item",
          "bom_item": "BOM item",
          "tax_inclusive": "Tax inclusive",
          "category_not_selected": "Category not selected",
          "minimum_one_rate_required": "Minimum one rate required",
          "yes": "Yes",
          "link_products": "Link products",
          "search_product": "Search Product",
          "printer_not_found": "Printer not found",
          "main_printer_ip": "Main printer ip",
          "generals": "Generals",
          "general": "General",
          "advanced": "Advanced",
          "print": "Print",
          "printer_ip_in_db_not_found": "Printer IP in db not found",
          "printer_local_print_db_not_found":
              "Printer local print db not found",
          "review_url_db_not_found": "Review URL db not found",
          "upi_db_not_found": "UPI id db not found",
          "cus": "CUS",
          "kot": "KOT",
          "ktm": "KTM",
          "custom_prints": "Custom Prints",
          "customer_print_with_review": "Customer print + review",
          "customer_print_with_amount": "Customer print + Amount",
          "customer_print_with_review_amount":
              "Customer print + review, Amount",
          "review_url_not_found_in_local_settings":
              "Review URL not found in local settings",
          "upi_id_not_found_in_local_settings":
              "UPI id not found in local settings",
          "is_bundle_product": "Is bundle product",
          "rate_description": "Rate description",
          "rate_description_is_empty": "Rate description is empty",
          "bundle_items_is_empty": "Bundle items is empty",
          "rate_unit_not_selected": "Rate unit not selected",
          "bundle_product_not_liked": "Bundle product not linked",
          "bundle_alternative_product_not_liked":
              "Bundle alternative product not linked",
          "add_products": "Add products",
          "add_alternatives": "Add alternatives",
          "alternatives": "Alternatives",
          "search_alternatives": "Search alternatives",
          "add_bom_item": "Add bom item",
          "bom_items": "Bom items",
          "bundles": "Bundles",
          "add_to_cart": "Add to cart",
          "product_not_added_to_cart": "Product not added to cart",
          "permission_denied_Connect_admin": "permission denied, Connect admin",
          "system_settings": "System settings",
          "shift_open": "Shift open",
          "shift_close": "Shift close",
          "multiplier_is_empty": "Multiplier is empty",
          "count_of": "Count of  ",
          "select_counter": "Select counter  ",
          "open_by": "Open by   ",
          "already_open_by": "Already Open by",
          "open": "Open",
          "close": "Close",
          "counter_not_selected": "Counter not selected",
          "shift_is_closed": "Shift is closed",
          "reports": "Reports",
          "sales": "Sales",
          "excl": "Excl",
          "sales_report": "Sales report",
          "sales_report_new": "Sales report new",
          "order_number": "Order number",
          "gross_amount": "Gross amount",
          "discount_amount": "Discount amount",
          "tax_amount": "Tax amount",
          "net_amount_1": "Net amount",
          'amount_from': 'Amount From',
          'amount_to': 'Amount To',
          'points_for_1_rs': 'POINTS   For 1 Rs',
          "balance_amount": "Balance amount",
          "payment_status": "Payment status",
          "online_reference": "Online reference",
          "delivered_by": "Delivered by",
          "count": "Count",
          "documents": "Documents",
          "gross": "Gross",
          "net": "Net",
          "purchase_detailed_report": "Purchase Detailed Report",
          "inv_date": "Inv Date",
          "grand_total": "Grand Total",
          "discount": "Discount",
          "start_at": "Start at",
          "first_invoice": "First invoice",
          "last_invoice": "Last invoice",
          "total_sales": "Total sales",
          "total_stock": "Total Stock",
          "kitchen_not_selected": "Kitchen not selected",
          "dinominations": "Dinominations",
          "empty_items": "Empty items",
          "shift": "Shift",
          "edit_success": 'Edit Success',
          'tax_total': 'Tax total',
          "shift_report": "Shift report",
          "starting_invoice": "Starting invoice",
          "closing_Invoice": "Closing invoice",
          "cash_balance": "Cash balance",
          "user_role": "User role",
          "paid": "Paid",
          "un_paid": "Un paid",
          "not_selected": "Not selected",
          "order_status": "Order status",
          "no_permission": "No permission",
          "shift_closed": "Shift closed",
          "sub_total": "Sub total",
          "tax_rate": "Tax rate",
          "tax_report": "Tax Report",
          "created_on": "Created On",
          "purchase_return_detailed_report": "Purchase Return Detailed Report",
          "tax_rate_is_empty": "Tax rate is empty",
          "account_master": "Account master",
          "purchase_report": "Purchase report",
          "supplier_name": "Supplier name",
          "invoice_number": "Invoice number",
          "balnce_amount": "Balnce amount",
          "general_expense": "General expense",
          "general_expense_create": "General expense create",
          "table_test": "Table Test",
          "closing_balance": "Closing balance",
          "delivery_boy": "Delivery boy",
          "e_wallet": "E-Wallet",
          "accept": "Accept",
          "reject": "Reject",
          "action": "Action",
          'status_id': "Status ID",
          "process": "Process",
          "split_to_bill_items": "Split to bill items",
          "discount_amt": "Discount Amt",
          "discount_percentage": "Discount %",
          "delivery_charge": "Delivery charge",
          "credit_limit_exceeded": "Credit limit exceeded",
          "tender_balance": "Tender balance",
          "partial": "Partial",
          "kitchen_request": "Kitchen Request",
          'do_you_want_to_accept_or_reject_the_request?':
              "Do you want to accept or reject the request ?",
          "merge": "Merge",
          "select_more_items_for_merge": "Select more items for merge",
          "wallet_amt": "Wallet amt",
          "wallet_coin": "Wallet coin",
          "coin_limit_exceeded": "Coin limit exceeded",
          "order_no": "Order NO",
          "payment_pending": "Payment pending",
          "summery": "Summary",
          "particulars": "Particulars",
          "sales_summery": "Sales summery",
          "account_summery": "Account summery",
          "cash_denomination": "Cash denomination",
          "expenses": "Expenses",
          "cash_sale": "Cash sale",
          "cash_short": "Cash short",
          "purchase_return_list": "Purchase Return List",
          "add": "Add",
          "main_item_qty_is_zero": "Main item qty is zero",
          "qty_is_zero": "Qty is zero",
          "cash_customer_registration": "Cash Customer Registration",
          "registered": "Registered",
          "mobile_already_exist": "Mobile already exist",
          "counter_cash_mismatch": "Counter cash mismatch",
          "do_you_sure_to_continue": "Do you sure to continue?",
          "error_occured_on_rate_linking": "Error occured on rate linking",
          'alert_message': 'Are you sure, You want delete this?',
          'active': "Active",
          'inactive': 'Inactive',
          'rootcause': 'Root Cause',
          'rootcause_create': 'Root Cause Create',
          'purchase_id': 'Purchase Id',
          'sales_cancel': 'Sales Cancel',
          'purchase_return_create': 'Purchase Return Create',
          'purchase_return_restaurant': 'Purchase Return Restaurant',
          'purchase_cancel': 'Purchase Cancel',
          'stock_adjestment': 'stock adjustment',
          'root_cause_id': 'Root Cause Id',
          'transaction_lists': 'Transaction List',
          'rootcause_not_found': 'Rootcause not found',
          'rootcause_id': 'Root Cause ID',
          'root_cause_not_found': 'Root Cause not found',
          'cancel_orders': "Cancel Orders",
          'product_already_exists': 'Product already exists',
          'table_id': "Table ID :",
          "table_name": "Table Name :",
          'product_name': 'Product Name',
          'cash_amount': "Cash amount",
          'freight': 'Freight',
          'order_cancel': "Order Cancel",
          'rootcause_not_selected': "Rootcause not selected",
          'split': "Split",
          'balance_is_not_zero': 'Balance is not zero',
          'min_two_split_items_required': "Min two split items required",
          'null_exception': "Null exception",
          'ok': "Ok",
          'print_not_possible_in_web': "Print not possible in web",
          'printer_not_configured': "Printer not configured",
          'do_you_want_to_continue': "Do you want to continue?",
          'shift_number': "Shift No.",
          'floors': 'Floors',
          'floor_name': 'Floor Name',
          'add_table': "Add table",
          'add_address': 'Add Address',
          'cost_Price': 'Cost Price',
          'minimum_one_address_required': "Minimum one address required",
          "day_close": 'Day Close',
          'transaction_date': 'Transaction Date',
          "purchase_return_report": "Purchase Return Report",
          "sales_return_report": "Sales Return",
          'detailed_report': "Sales Detailed Report",
          "purchase_view": "Purchase View",
          'purchase_is_empty': 'Purchase is Empty',
          'cost_price': 'Cost Price',
          "product_details": "Product Details",
          'purchase_list': 'Purchase List',
          "sales_invoice_report": "Sales Invoice Report",
          "sales_count": "Sales count",
          "total_amount": "Total Amount",
          "sales_detailed_report": "Sales Detailed Report",
          "sales_return_detailed_report": "Sales Return Detailed Report",
          "no_filter_found": 'No filter found',
          "purchase_details": "Purchase Details",
          "supplier_address": "Supplier Address",
          "supplier_contact_no": "Supplier Contact No",
          "freight_charges": "Freight Charges",
          "product_id": "Product ID",
          "variant_name": "Variant Name",
          "variant_qty": "Variant Qty",
          "sale_total": "Sale Total",
          "credit_amount": "Credit Amount",
          "ps": 'PS',
          "purchase_no": "Purchase No",
          "sales_no": "Sales no",
          "provider_details": "Provider Details",
          "create_by": 'Create by',
          'product_no': 'Product no',
          'no_products_found': "No Products Found",
          'exceeded_credit_limit': "Exceeded credit limit",
          "tax_collected": "Tax Collected",
          "tax_paid": "Tax Paid",
          "expense_report": "Expense Report",
          "expense_account": "Expense Account",
          "re": "",
          "select_product": "Select Product",
          "select_rootcause": "Select Rootcause",
          "select_supplier": "Select Supplier",
          "transactionType": "TransactionType",
          "sales_details": 'Sales details',
          "sales_summary": 'Sales summary',
          "promotion_details": 'Promotion details',
          "category_details": 'Category details',
          "account_summary": 'Account summary',
          "payment_summary": 'Payment summary',
          "cancelled_summary": 'Cancelled summary',
          "purchase_summary": 'Purchase summary',
          "cancelled_details": 'Cancelled details',
          "cash_summary": 'Cash summary',
          "less": 'Less',
          "vendor": "vendor",
          "no_bill_associated_with_selected_customer":
              "No bill associated with selected customer",
          "select_start_date": "Select start date",
          'only_alphabetic_characters_allowed':
              'Only alphabetic characters allowed',
          'maximum_of_10_characters_allowed':
              'Maximum of 10 characters allowed',
          "kot_notes": "KOT Notes",
          "order_not_createdd_yet": "Order not created yet",
          "notes": "Notes",
          "is_default": "Is default",
          "edit_address": "Edit address",
          "invalid_product_found": "Invalid product found",
          "main_item_qty_is_empty": "Main item qty is empty",
          "account_ledgers": "Account ledgers",
          "account_ledger_reports": "Account ledger reports",
          "cant_split_paid_order": "Cannot split paid order",
          "cant_split_delivery_charge_applied_order":
              "Cannot split delivery charge applied order",
          "cant_merge_paid_order": "Cannot merge paid order",
          "cant_merge_delivery_charge_applied_order":
              "Cannot merge delivery charge applied order",
          "outstanding_report": "Outstanding Report",
          "outstanding_payable_report": "Outstanding Payable Report",
          "outstanding_payable": "Outstanding Payable",
          "outstanding_receivable": "Outstanding Receivable",
          "outstanding_payable_detailes": "Outstanding Payable Detailes",
          "outstanding_receivable_detailes": "Outstanding Receivable Detailes",
          "saled_id": "Sales Id",
          "invoice_amount": "Invoice Amount",
          "paid_amount": "Paid Amount",
          "bill_amount": "Bill Amount",
          "shfit_report": "Shfit Report",
          "select_different_store_locations":
              "Select different stock locations",
          "select_store_location": 'Select Store Location',
          "please_enter_value": "Please enter a value",
          "stock_from": "Stock From",
          'stock_to': "Stock To",
          'save_sample_sheet': "Save sample sheet",
          'si_no': "SI No",
          "stock_location": "Stock Location",
          "successfully_updated": "Successfully Updated",
          "sales_id": "Sales Id",
          "success_edit": "Success Edit",
          "from_stock_location": "From Stock Location",
          "to_stock_location": "To Stock Location",
          "total_bill_amount": "Total Bill Amount",
          'add_the_excel_file': "Add the Excel File",
          "total_paid_amount": "Total Paid Amount",
          "total_balance_amount": "Total Balance Amount",
          "sale_type_not_found": "Sale type not found",
          "price_not_linked": "Price not linked",
          "price_not_linked_items_found_in_cart":
              "Price not linked items found in cart",
          "sign": "Sign",
          "employee": "Employee",
          'cell_at_row': "Cell at Row",
          'invalid_numeric_value_in_cell_at_row':
              'Invalid numeric value in cell at row',
          'and_column': 'and Column',
          'invalid_value_in_cell_at_row': 'Invalid value in cell at Row',
          'is_empty': 'is empty',
          "table_selection": "Table Selection",
          "customer_data": "Customer Data",
          "online_order": "Online Order",
          "table_is_empty": "Table is empty",
          "drag_and_drop_for_file_uploading":
              "Drag and drop for file uploading",
          "permissions": "Permissions",
          "please_update_your_app_for_better_experience":
              "Please update your app for better experience",
          "review_qr_code": "Review QR code",
          "amount_qr_code": "Amount QR code",
          "amount_and_review_qr_code": "Amount and Review QR code",
          'select_drop_down_value': 'Select drop down value',
          "email_report": "Email Report",
          "add_bom_items": "Add BOM Item",
          "add_rates": "Add Rate",
          "add_taxes": "Add Tax",
          "local_name": "Local Name",
          "allow_to_sale": "Allow To Sales",
          "allow_to_purchase": "Allow To Purchase",
          "supplier_details": "Supplier Details",
          "purchase_detailes": "Purchase Detailes",
          "payment_detailes": "Payment Detailes",
          "added_success_fully": "Added Successfully",
          "add_excel_file": "Add Excel File",
          "get_sample_excel": "Get Sample Excel",
          "should_not_be_empty": "Should Not Be Empty",
          "should_contain_only_yes/no_or_y/n":
              "Should Contain Only Yes/No or Y/N",
          "this_column_is_not_needed": "This Column Is Not Needed",
          "please_add_excel_first": "Please Add Excel First",
          "should_be": "Should Be",
          "please_correct_the_errors_and_resubmit":
              "Please Correct The Errors And Resubmit",
          "please_add_excel_file_only": "Please Add Excel File Only",
          "add_only_one_file": "Add Only Single File",
          "no_data_found": "No Data Found",
          "row_": "Row",
          "col_": "Column",
          "_and": "And",
          "the_": "The",
          "is_": "Is",
          "are_": "Are",
          "missing_": "Missing",
          "seater": "Seater",
          "item_discount": "Item discount",
          "rate_adjustment": "Rate djustment",
          "Customer_detailes": "Customer Detailes",
          'order_history': "Order History",
          'sale_detailed_report': 'Sale Detailed Report',
          'print_preview': ' Print Preview',
          'test_print': 'Test Print',
          'quick_links': 'Quick Links',
          'customer_print': 'Customer Print',
          'kot_print': 'KOT Print',
          'day_report': 'Day Report',
          'masters': 'Masters',
          'account_not_mapped': 'Account not mapped',
          'without_free': 'Without free',
          'product_with_free': 'Product With free',
          'if_it_has_any_free': 'If it has any free',
          'please_turn_on_the_switch': 'Please turn on the switch',
          'product_not_selected': 'Product not selected',
          'variane_not_selected': 'Variant not selected',
          'normal_erp': 'Normal ERP',
          'open_cash_drawer': 'Open cash drawer',
          'already_completed_order': 'Already completed order',
          'auto_customer_print_on': 'Auto customer print on',
          'auto_customer_print_off': 'Auto customer print off',
          'editted_order_must_submit_before_split':
              'Editted order must submit before split',
          'editted_order_must_submit_before_print':
              'Editted order must submit before print',
          'please_wait_order_creation_is_in_progress':
              'Please wait, order creation is in progress',
          'coordinator_print': 'Coordinator print',
          'favorites': 'Favorites',
          'user_deleted': 'User deleted',
          'user_is_inactive': 'User is inactive',
          'order_editted_by_another_user':
              'Order editted by another user, please refresh',
          'order_under_processing_please_do_again':
              'Order under processing, please do again',
          'bill_number': 'Bill number',
          'forceful_logout': 'Forceful logout',
          'are_you_sure': 'Are you sure',
          'are_you_sure_to_do_force_logout': 'Are you sure to do force logout',
          'kot_nos': 'Kot nos',
          'kot_update': 'Kot update',
          'kot_status': 'Kot status',
        },
        'hi_IN': {'hellow': 'Hellow in hindi'},
      };
}
